# Generated by Django 4.1.1 on 2022-09-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('price_rubles', models.IntegerField()),
                ('delivery_date', models.DateField()),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('is_worked_out', models.BooleanField(default=False)),
                ('record_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleAPI.record')),
            ],
        ),
    ]
